# Generated by Django 3.1.4 on 2021-01-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210112_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymeny',
            new_name='payment',
        ),
    ]
